# 2014-7: Revolutionary Thinking
# Imagine there are two circles that are tangent to one another. One circle is stationary, the other can "roll" around the stationary circle.
# Write a function which takes the diameters of the stationary and mobile circles and returns the number of revolutions the mobile must traverse until the tangent points meet again.

# Experimental!
Revolutions ← ÷⤙(÷⊃∨×)

⍤⤙≍ 1 Revolutions 10 10 # identically sized circles
⍤⤙≍ 2 Revolutions 10 5  # a mobile circle that's half the size needs to make 2 revolutions
⍤⤙≍ 5 Revolutions 5 7   # a mobile circle of diameter 7 needs to make 5 revolutions around a stationary circle of diameter 5
