# 2016-10: Order Total
# Suppose you have a numeric vector that is the list of prices for a set of retail products. 
# You also have a numeric vector that is the number ordered of each product. 
# Write a function that takes as its right argument a vector of prices and as its left argument a numeric vector that indicates the number ordered and returns the total cost for the order.

Total ← /+×

⍤⤙≍ 18.93 Total [5 0 2] [2.99 4.99 1.99]
⍤⤙≍ 0 Total [0 0 0] [2.99 4.99 1.99]
